version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - ./mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress_db
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    phpadmin:
        depends_on:
        - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
        - '8080:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
    wordpress:
        depends_on:
        - db
        volumes:
            - ./www:/var/www/html
        image: wordpress:latest
        ports:
        - "8000:80"
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: root
            WORDPRESS_DB_NAME: wordpress_db